### ISSUE TITLE
New version should use a better build tool like Puppet or Chef to provision machines or build VM's

### ISSUE THREAD

**Issue by freibuis** [E-F-A/v4#1]
Times have changed in the last 5 years,,

continuing down the path or scripts for a project like this makes no sense. 

I would suggest moving to a state management system like **Puppet** or **chef**. ( i am biased towards **puppet**)

if you use puppet forge you can leverage what other ppl have already built to save time

example

``` puppet
#set root password
user {'root':
  ensure   => present,
  password => pw_hash('EfaPr0j3ct', 'SHA-512', 'mysalt') ,
}

#make sure directories are availble
file { ['/var/log/EFA' , '/usr/src/EFA']: 
  ensure => 'directory',
}
#install spam ass assin
package {'spamassassin':
  ensure => present,
}

#example of having Fav icon in 3 places
#/bin/cp -f favicon.ico /var/www/html/mailscanner/
#/bin/cp -f favicon.ico /var/www/html/mailscanner/images
#/bin/cp -f favicon.ico /var/www/html/mailscanner/images/favicon.png

file {'/var/www/html/mailscanner/',
       '/var/www/html/mailscanner/images',
       '/var/www/html/mailscanner/images/favicon.png']:
  ensure => 'present',
  source => '/files/favicon.ico',
}
```

This allows for faster iterations, custom builds. also package version locking or package upgrading. oh and the best thing.. you could get this to work across most unix based platforms with ease!

**Comment by shawniverson** [comment]
Thanks for idea, much appreciated :)  We are looking at new options for v4.

**Comment by shawniverson** [comment]
With full rpm support, I plan to provide a sample ansible playbook to mass deploy eFa in a large environment.

**Comment by shawniverson** [comment]
Added ansible support
