### ISSUE TITLE
efa4 eFanint can not select network interface when having more than one network interface

### ISSUE THREAD

**Issue by yoke88** [E-F-A/v4#119]
using the latest commit：ce4429d35b54d1c7ca2bdc771bbf0574a40c11a7

![default](https://user-images.githubusercontent.com/3146226/47631000-dfafc200-db7e-11e8-9ce7-a1014d8a5926.JPG)

**Comment by yoke88** [comment]
if i configure it from console using /usr/sbin/eFa-Init . error occurs.

![default](https://user-images.githubusercontent.com/3146226/47631713-0f13fe00-db82-11e8-8322-5de5fe711e71.JPG)

**Comment by shawniverson** [comment]
Fixed in commit 6cd6880f20f5f97d7a66a820ac44046c9555fc97
