### ISSUE TITLE
Inline Signature not possible for GTLD

### ISSUE THREAD

**Issue by ictinc** [E-F-A/v4#140]
Hi there,
I'm trying to add my domains to inline signatures. All my .com and .nl domains work flawlessly. When I try to add my GTLD (.hosting) is where it goes wrong.

1) I choose 'n' to add new mail domain rule
2) I enter the domain "domain.hosting" (without quotes)
3) I receive error: ERROR: The domain  seems to be invalid ERROR: please re-enter the domain

This only happens with GTLD and not normal TLDs.

**Comment by shawniverson** [comment]
Inline sigs configuration is pulled for release.  Sigs will need to be configured manually.

https://github.com/E-F-A/v4/commit/f4654e20cf8844cb09aab1d5dde56a796cbf9401
