### ISSUE TITLE
Default filetype.rules file missing ipv4 localhost entry

### ISSUE THREAD

**Issue by sriccio** [E-F-A/v4#165]
Hello,

I'm currently installing a new fresh eFa 4 box for replacing our eFa 3.

While looking at the default configuration after the install, I saw that in the file `filetype.rules` there are only the `ipv6` localhost entry:
```
From:   ::1     /etc/MailScanner/filetype.rules.allowall.conf
FromOrTo:       default /etc/MailScanner/filetype.rules.conf
```

While in `filename.rules` there is also the `ipv4` local host entry:
```
From:   127.0.0.1       /etc/MailScanner/filename.rules.allowall.conf
From:   ::1     /etc/MailScanner/filename.rules.allowall.conf
FromOrTo:       default /etc/MailScanner/filename.rules.conf
```

Not really sure if that could cause a problem, but I wanted to let you know :)

**Comment by shawniverson** [comment]
Fixed in commit ecb525f952d410aa3a6e85ab0c0f9d0693643f95
