### ISSUE TITLE
Improve changing IP in command line interface

### ISSUE THREAD

**Issue by deajan** [E-F-A/v4#175]
Hello,

Just freshly installed my first EFAv4, and noticed something quite unfriendly when changing the IP of the appliance in the CLI.
When changing IP, the script tries to reload the new IP before I happen to be able to enter a netmask or gateway. The same happens when trying to change the latter two parameters.

This behavior makes the appliance unresponsive to network connections, so changing IP requires a console connection.

Shouldn't the script ask for all network details (ip, mask, gw, dns) before validating the changes ?

Best regards.

**Comment by headhunter911** [comment]
@shawniverson I am going to work on this problem.  My idea is to pull a temporary copy of efa-configthen create a save / discard option at the end of the ip settings.  On a save it'll replace the original efa-config and then the ip settings change will be started pulling the information directly from efa-config.

**Comment by shawniverson** [comment]
@headhunter911 Sounds like a good idea. I look forward to seeing a PR. If you have any questions let me know.

**Comment by shawniverson** [comment]
@headhunter911 any progress, by chance? No rush, just wondering if I should skip over this issue and work on others.

**Comment by shawniverson** [comment]
Proceeding with enhancement

**Comment by shawniverson** [comment]
Added in commit ea22efeb72356ffa9da1ee3bfe273b8f6dca3d3b

**Comment by deajan** [comment]
Thanks ;)

**Comment by headhunter911** [comment]
I was out of town last week, looks liek you beat me to it.  Thanks.  I'll look for something else to help with
