### ISSUE TITLE
Email throttling & manual reschedule delivery

### ISSUE THREAD

**Issue by deajan** [E-F-A/v4#191]
Hello,

I need to send about 100 emails to the same domain, which accepts low connection concurrency from the same IP, via a standard gui MUA.

I had about 70 mails stuck in the postfix queue, but couldn't find a way to schedule them for delivery.
I ended up re-scheduling them via the following shell command

```for i in $(postqueue -p | grep '@' | cut -f1 -d' '); do sleep 5; postqueue -i $i; done```

While this is a low tech solution, I wondered why there wasn't any way to reschedule mails in the GUI, or even delete them from the queue.

Also, pretty sure this hasn't to do with E-F-A itself, but here's another problem I found while rescheduling:
I added the following to my main.cf in order to make sure postfix won't deliver more than 1 mail every 3 seconds to the same domain:

```
smtp_destination_rate_delay = 3s
smtp_destination_concurrency_limit = 1
```

After reloading postfix, I flushed the postfix queue with `postqueue -f`, only to discover that from 70 mails, only 3 were sent, and all other had a message "slow down connections" from the remote MTA.
This indicates that my settings didn't probably work. Any ideas ?

Also, will those settings survive E-F-A upgrades ?

Best regards.

**Comment by shawniverson** [comment]
Yes, those settings should be preserved.  There are few other things that have to be done besides those postfix settings.  For example you have 4 postfix threads, so you have to chop them down to 1 thread so you aren't sending 4 emails, 1 per thread.

**Comment by deajan** [comment]
Thanks ;)
Would you mind giving me advice on what other settings are required ?

**Comment by shawniverson** [comment]
I would do a transport specific override so that you don't affect your entire system.

/etc/postfix/main.cf
```
...
slow_destination_concurrency_limit = 1
slow_initial_destination_concurrency = 1
...
```

/etc/postfix/master.cf
```
...
slow      inet  n       -       n       -       1       smtpd
```

/etc/postfix/transport
```
example.com     slow:
```

**Comment by deajan** [comment]
Thanks ;)
