### ISSUE TITLE
update-4.0.3.sh / PR #202 and (#203)

### ISSUE THREAD

**Issue by johnjore** [E-F-A/v4#206]
Hi!

Still trying to wrap my head around what scripts run on new install vs updates vs build vs devbuild etc.

I suspect PR #202 needs duplicating in update-4.0.**4**.sh as update-4.0.**3**.sh (line 288) probably has the same issue? I'm guessing modifying update-4.0.3.sh is not a good idea, but get fixed in update-4.0.4.sh?

Is update-4.0.3.sh a copy of update-4.0.2.sh, but with additional tweaks, i.e. PR #203 needs adding as well, or?

**Comment by shawniverson** [comment]
Added qualifier to eFa-Post-Init for CentOS 7 builds for SA 566228b24f495eb839266ad1d61876d6a2cf4098
Duplicated PR #202 to update-4.0.3.sh b94199fc4c11cacd7244b7e3813e63893e3d763b
PR#203 doesn't need added to update, in my opinion.  This is just to get the token db going early.

4.0.4 doesn't exist yet.  Each of these is a new (minor) version.  I tend to only do these when I add new functionality.
Within each version are releases, and the updates are cumulative within each release, which include all the relevant updates in the update file from prior versions. This provides a basic level of compliance of various fixes as updates get applied with each release. As a general rule, any changes made to need to happen both in the eFa source and the update file, with the exception of files listed in the eFa rpm SPEC, which update automatically (i.e. eFa-Configure scripts)

build.sh is the way sysadmins deploy eFa in production.  Updates happen via yum.
devbuild.sh is how folks like you and me build the packages for eFa locally and dev/test

**Comment by johnjore** [comment]
All good, this "ticket" was created as a place holder, as I didn't know where or how my various fixes would move from devbuild.sh and func_ scripts to the packages and already deployed installations. Just close it if all is ok and tracked / done by yourself.

As a side note, I've completed my migration from v3 to v4 (x64) and then on to arm64. All in all it went pretty smooth, thanks for all your hard work.
