### ISSUE TITLE
CentOS 8 / bug in func_setipsettings / PREFIX vs NETMASK / systemctl

### ISSUE THREAD

**Issue by johnjore** [E-F-A/v4#207]
There is no 'network.service' on 8:
`Failed to restart network.service: Unit network.service not found.`

Google tells me these should work:
*	systemctl restart NetworkManager 
*	nmcli device reapply device 
*	nmcli con down device && nmcli con up device

However, it looks like "PREFIX" is favoured over "NETMASK" and "PREFIX" is inserted when restarting the interface. 

If 7 supports PREFIX, then maybe better to use that instead of trying to use both PREFIX and NETMASK in the script and the same for restarting the service. Not sure which of the 3x above work on 7 and 8.

**Comment by shawniverson** [comment]
Replaced with NM in commit 168500171febef11a3292c45aa9194358e1ded73

Going to do some testing to see how to best handle the PREFIX/NETMASK stuff

**Comment by shawniverson** [comment]
Fixed in commit 796daab061c7d08c2f22bedf86fb4b4af3ee13a4
