### ISSUE TITLE
CentOS 8 minimal - missing rsyslog causes empty log

### ISSUE THREAD

**Issue by cbrandlehner** [E-F-A/v4#210]
When installing EFA out of the box on CentOS 8 minimal, you will find that /var/log/messages and /var/log/maillog are EMPTY even if EFA processes mail.

I found that neither syslog nor rsyslog are running on the installation out of the box.

I used this tutorial to install and enable rsyslog and it fixed the issue.
https://linuxconfig.org/install-syslog-on-redhat-8

**Comment by shawniverson** [comment]
Required in commit eec90eb666fb9273df3ff826f83c3cf9ba7a4bb1
