### ISSUE TITLE
Repo certificate expired

### ISSUE THREAD

**Issue by sriccio** [E-F-A/v4#249]
Hello,

I just want to let you know that the certificate for dl.efa-project.org is expired and prevents running a yum update.

Kind regards and great year 2021 to all.

```
[root@mx2 ~]# yum update
Loaded plugins: fastestmirror
Determining fastest mirrors
Could not retrieve mirrorlist https://dl.efa-project.org/rpm/eFa4/mirrors-eFa error was
14: curl#60 - "Peer's Certificate has expired."
```

EDIT: Temporary workaround is to add sslverify=0 to the repo file

**Comment by shawniverson** [comment]
Fixed.
