### ISSUE TITLE
MariaDb error installing eFa-4.0.4

### ISSUE THREAD

**Issue by nicolapiazzi** [E-F-A/v4#279]
Installing Efa I have this error, using fresh CentOS-8.3.2011-x86_64

[eFa] If these settings are correct type 'OK' to continue.
[eFa] if there is an error enter the number you want to change.
[eFa] : OK
[eFa] - Starting MariaDB and Configuring
ERROR 1064 (42000) at line 20: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
lastsent TIMESTAMP NOT NULL DE...' at line 11
[eFa] - Configuring hostname and domainname
[eFa] - Setting DNS
Created symlink /etc/systemd/system/multi-user.target.wants/unbound.service → /usr/lib/systemd/system/unbound.service.
[eFa] - Setting IP settings
[eFa] - Generating SSH Host keys
Top

**Comment by nicolapiazzi** [comment]
But after installation seems that last_update colums is already as we want, so this seems a minor bug


MariaDB [mailscanner]> describe maillog;
+-----------------+---------------------+------+-----+---------------------+-------------------------------+
| Field | Type | Null | Key | Default | Extra |
+-----------------+---------------------+------+-----+---------------------+-------------------------------+
| maillog_id | bigint(20) unsigned | NO | PRI | NULL | auto_increment |
| .....
| last_update | timestamp | NO | | current_timestamp() | on update current_timestamp() |
| messageid | longtext | YES | | NULL | |
+-----------------+---------------------+------+-----+---------------------+-------------------------------+
43 rows in set (0.002 sec)

**Comment by shawniverson** [comment]
Fixed in commit 0c3f19e69ca285266e35d5a3a220b8b415825fe1 will go out with next update
