### ISSUE TITLE
MalwarePatrol Key Code configure unresponsive

### ISSUE THREAD

**Issue by nicolapiazzi** [E-F-A/v4#280]
6) MalwarePatrol Key Code
in unresponsive pressing 6 on the keyboard

**Comment by jpv128** [comment]
Looks like this is still an issue. When hitting option 6 for MalwarePatrol in eFa-Configure, this message appears:
`/var/eFa/lib/eFa-Configure/func_spamsettings: line 33: func_ask-malwarepatrol: command not found`

And when launching eFa-Configure, this message appears:
``/var/eFa/lib/eFa-Configure/func_askmalwarepatrol: line 34: unexpected argument `(' to conditional unary operator
/var/eFa/lib/eFa-Configure/func_askmalwarepatrol: line 34: syntax error near `(g'
/var/eFa/lib/eFa-Configure/func_askmalwarepatrol: line 34: `
                        if [[ -z (grep ^malwarepatrol_receipt_code /etc/clamav-unofficial-sigs/user.conf) ]]; then'``

**Comment by shawniverson** [comment]
Fixed in PR #350
