### ISSUE TITLE
Incoming mail with DKIM validation always fail due DNSSEC unbound issue

### ISSUE THREAD

**Issue by hunter-nl** [E-F-A/v4#288]
All my incoming mail is validated with openDKIM. The result is always 'failed', regardless if domain where the mail is coming from is DNSSEC enabled or not.
e.g.
```
Authentication-Results: mail.example.nl;
     dkim=fail reason="signature verification failed" (1024-bit key; unprotected) header.d=mail.somedomain.nl header.i=@mail.somedomain.nl header.a=rsa-sha256 header.s=sim header.b=cczsPq2v
```
The "unprotected" means it can not being validated by DNSSEC. I figured it out that the unbound is forwarding the requests to my own DNS infrastructure. This DNS infrastructure is working correctly with DNSSEC and when using dig command to validate the DNSSEC of the domain it is responding with the AD flag. But unbound does never respond with the AD flag. So openDKIM thinks the DNSSEC is failing on the request for the signature. DKIM will then always failing the validation also when signature is valid.
Is there a way to solve this?

**Comment by shawniverson** [comment]
I think you need to enable DNSSEC support in unbound.

**Comment by hunter-nl** [comment]
DNSSEC is enabled in Unbound, but Unbound will not return the AD flag (dnssec has been valid validated) when unbound is configured with forwarders. I've changed the opendkim.conf file now with Nameservers to use directly my own DNS infrastructure instead of Unbound. I would like to disable Unbound completely but then Watchdog is interfering.

**Comment by shawniverson** [comment]
Understood, you can take unbound out of the eFa-Monitor script that cron references.

I'll tag this for enhancement to disable unbound
