### ISSUE TITLE
Installer script fails + eFa-Init file is not present

### ISSUE THREAD

**Issue by yokiyoki22** [E-F-A/v4#326]
Hello,
I tried installing eFa4 on a fresh Centos 7 machine via the installer script.
`curl -sSL https://install.efa-project.org | bash`

The script failed at the "Installing eFa packages" step.
I tried installing manually to understand the problem:
`yum install eFa`
> Error: Package: 1:eFa-4.0.4-13.eFa.el7.noarch (eFa4)
           Requires: mariadb101u-server >= 1:10.1.35-1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

(This issue was not present last week when I ran the same script)

I solved this by enabling the **ius-archive** repository with
`yum-config-manager --enable ius-archive`

Running the script again successfully finished the installation but I was not given the Yes/No prompt for rebooting.

Upon reboot I was not presented with the modified root password, so I logged in with the original one.
After logging in, an error was printed:

> -bash: /usr/sbin/eFa-Init: No such file or directory

Other scripts (like eFa-Configure) are present in the /usr/sbin directory.
I see that some changes to the eFa-Init were committed 6 days ago, did this break the installation process?

**Comment by yokiyoki22** [comment]
I tried installing once again today:

The **ius-archive** repo was still needed as a fix
The prompt for reboot did not appear
root password was not modified
The _eFa-Init_ file was present, and ran correctly upon reboot

Everything seems to be running as intended now

**Comment by shawniverson** [comment]
Working on this now.

**Comment by shawniverson** [comment]
Fixed and repo updated.
