### ISSUE TITLE
OpenDMARC package 1.4.1 must upgrade the existing db schema

### ISSUE THREAD

**Issue by hunter-nl** [E-F-A/v4#327]
Since openDMARC package has been updated to version 1.4.1, opendmarc-import is failing due the db schema has been changed. The package upgrade should update the schema of the OpenDMARC db.

**Comment by arthur-lbchn** [comment]
Not sure if it's related, however, we're starting to received dozen of notifications that opendmarc service is killed:

id b4f4cf333f0fd361ed4068f973213ea196e4d8f3
reason:         opendmarc killed by SIGABRT
time:           Wed 16 Jun 2021 09:34:42 PM CEST
cmdline:        /usr/sbin/opendmarc -c /etc/opendmarc.conf -P /run/opendmarc/opendmarc.pid
package:        opendmarc-1.4.1-1.el7
uid:            988 (opendmarc)
count:          109
Directory:      /var/spool/abrt/ccpp-2021-06-16-21:34:42-31528

**Comment by shawniverson** [comment]
Fixing in commit 0332ed53279ca4d7ba6361e3fc73bfc684c0c036
