### ISSUE TITLE
CustomAction overwritten

### ISSUE THREAD

**Issue by yokiyoki22** [E-F-A/v4#335]
Hello,

I am using a customized version of the CustomAction script to deal with spam notifications.

However, the file at `/usr/share/MailScanner/perl/custom/CustomAction.pm` gets overwritten and restored to the original version *at random*. This has happened 3 times in 2 weeks, and with no apparent pattern: once at 4am, once in the afternoon, etc..

I'm currently unable to identify which process is overwriting the file, could it be some autoupdate or backup feature that EFA4 uses by default? My workaround is periodically copying the customized script on top of the original...

Thanks in advance

**Comment by shawniverson** [comment]
Hello, CustomAction.pm is part of the eFa rpm package.  As you are customizing it, any update to eFa would overwrite this file during an update. We would need to find a way to avoid that while at the same time not leaving others with an outdated CustomAction.pm.  Due to the way this directory and file works, I can't rename or flag it for noreplace. Perhaps I could version the file and tag it so that you can mark yours as not the eFa version by removing the tag.

**Comment by yokiyoki22** [comment]
Is there any way to disable these automatic updates?

Also, iirc the current CustomAction does nothing more than the equivalent "Store Notify"
Why not leave this file open for customizations?

**Comment by shawniverson** [comment]
You can disable yum-cron or dnf-automatic, depending on your distro.

CustomAction.pm in eFa exposes additional parameters for use for spam and nonspam notifications.

**Comment by yokiyoki22** [comment]
I see, some more questions then: is it possible to notify only internal domains about both incoming and outgoing spam? Sending a notification to spammers is not really recommended, as you would confirm that the mailbox is active.
I also need to send all notifications to a specific mail box (spam@mydomain.tld), except for a list of "advanced" users.

This is what I did with my CustomAction. I'm not a Perl expert, but if these features are not available I could share the code so that you could add the option with some flag/parameter.

**Comment by shawniverson** [comment]
Yes, with a ruleset you can notify only internal domains.  Not using a ruleset, as you point out, leads to backscatter.

I would be happy to include your code into CustomAction.pm as a feature. This sounds beneficial. I am also rethinking CustomAction.pm in general. Ideally if I could avoid it altogether as you suggested, perhaps by making a separate custom module, we could have the best of both worlds.

**Comment by yokiyoki22** [comment]
I completely missed the fact that rulesets are allowed in this configuration! I guess my question is not really relevant.
I will email you my custom code.
