### ISSUE TITLE
Installation failure on Centos 7

### ISSUE THREAD

**Issue by lucap12** [E-F-A/v4#340]
hello
i receive the below  error when i attempt to do a fresh install on a centos 7
i have see some change on rpmbuild in the last hours
[Mariadb 10.4 for CentOS 7](https://github.com/E-F-A/v4/commit/ae6a1ad578952c8b07239a281d1c883b49089b8b)
i have to wait repository propagation ?
Best regards Luca 

-----------------------------------------------------------------------
tail -n 20  /var/log/eFa/build.log
--> Running transaction check
---> Package eFa.noarch 1:4.0.4-32.eFa.el7 will be installed
--> Processing Dependency: mariadb102-server >= 3:10.2.30-1 for package: 1:eFa-4.0.4-32.eFa.el7.noarch
--> Processing Dependency: mariadb102-libs >= 3:10.2.30-1 for package: 1:eFa-4.0.4-32.eFa.el7.noarch
--> Processing Dependency: mariadb102-common >= 3:10.2.30-1 for package: 1:eFa-4.0.4-32.eFa.el7.noarch
--> Processing Dependency: mariadb102 >= 3:10.2.30-1 for package: 1:eFa-4.0.4-32.eFa.el7.noarch
---> Package python-ply.noarch 0:3.4-11.el7 will be installed
--> Finished Dependency Resolution
Error: Package: 1:eFa-4.0.4-32.eFa.el7.noarch (eFa4)
           Requires: mariadb102 >= 3:10.2.30-1
Error: Package: 1:eFa-4.0.4-32.eFa.el7.noarch (eFa4)
           Requires: mariadb102-libs >= 3:10.2.30-1
Error: Package: 1:eFa-4.0.4-32.eFa.el7.noarch (eFa4)
           Requires: mariadb102-server >= 3:10.2.30-1
Error: Package: 1:eFa-4.0.4-32.eFa.el7.noarch (eFa4)
           Requires: mariadb102-common >= 3:10.2.30-1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
2022.07.05-03:15:16 - ERROR: eFa4 failed to install
2022.07.05-03:15:16 - ^^^^^^^^^^ SCRIPT ABORTED ^^^^^^^^^^

           Requires: mariadb102-server >= 3:10.2.30-1
Error: Package: 1:eFa-4.0.4-32.eFa.el7.noarch (eFa4)
           Requires: mariadb102-common >= 3:10.2.30-1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
2022.07.05-03:15:16 - ERROR: eFa4 failed to install
2022.07.05-03:15:16 - ^^^^^^^^^^ SCRIPT ABORTED ^^^^^^^^^^

**Comment by shawniverson** [comment]
Fixes currently in the testing repo, expect prod to receive them in 24 hours.

**Comment by lucap12** [comment]
thanks !

**Comment by shawniverson** [comment]
Fixes deployed, please git a try. @lucap12

**Comment by lucap12** [comment]
The setup start successfull
