### ISSUE TITLE
Support for EL 9

### ISSUE THREAD

**Issue by leetsin** [E-F-A/v4#347]
Kindly add support for EL 9 Releases.
Some popular ones are RHEL 9.1, Alma Linux 9.1, Rocky Linux 9.1, and Oracle Linux 9.1.

**Comment by shawniverson** [comment]
Working toward that end.  MailScanner and friends first have to work on EL9 before eFa can, so working on that first.

**Comment by leetsin** [comment]
Thanks a lot 😎

**Comment by shawniverson** [comment]
https://github.com/E-F-A/eFa5

**Comment by bilias** [comment]
Why Stream? Why not a long supporting (and stable) release like rocky or almalinux?

**Comment by shawniverson** [comment]
@bilias All EL9 variants are supported, not just Stream.
