### ISSUE TITLE
Updating GeoIP database gets stuck while unpacking

### ISSUE THREAD

**Issue by Zennate** [E-F-A/v4#368]
OS: CentOS Linux 7.9.2009
Software Version: MailWatch for MailScanner v1.2.21 running on eFa-4.0.4
A valid free GeoLite2 License is installed.

Description:
Manually updating the GeoIP Database by accessing https://<hostname>/mailscanner/geoip_update.php does not update the GeoIP Database. The WebIU only shows the following output and freezes indefinitely:
```
Downloading file, please wait...
Download complete, unpacking files...
```

Running /usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php manually gives you the following output:
```
Downloading file, please wait...
Download complete, unpacking files...
PHP Fatal error:  Uncaught UnexpectedValueException: internal corruption of phar "/var/www/html/mailscanner/temp/GeoLite2-Country.tar.gz" (truncated entry) in /usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php:155
Stack trace:
#0 /usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php(155): PharData->__construct()
#1 {main}
 thrown in /usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php on line 155
```

The script creates the empty file /var/www/html/mailscanner/temp/GeoLite2-Country.tar.gz before halting.
`if (function_exists('fsockopen') || extension_loaded('curl')) {` returns `true` so curl is used instead of wget.

Current workaround:
Force the use of wget instead of curl, and add double quotes around the URL of the wget request like so:
`'wget ' . $proxyString . ' -N ' . $files_base_url . $file['path'] . ' -O ' . $file['destination'],`
->
`'wget ' . $proxyString . ' -N "' . $files_base_url . $file['path'] . '" -O ' . $file['destination'],`

Without the double quotes, wget will try to access https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country and ignore every parameter after the first ampersand, including license_key.

**Comment by shawniverson** [comment]
Fixed in v4.0.4-42
