### ISSUE TITLE
build eFa

### ISSUE THREAD

**Issue by biaxz** [E-F-A/v4#92]
Hi.
@shawniverson It's open project or closed?

I am interested to build from scratch, but there seems to be no explanation whatsoever from this repository, and some file missing.

Thanks.

**Comment by shawniverson** [comment]
@biaxz This is an open project.

The project is in alpha.  There is no how-to because it is not ready.  I'm not sure what you mean that some files are missing.

See:
https://raw.githubusercontent.com/E-F-A/v4/master/build/build.bash
https://forum.efa-project.org/viewtopic.php?f=5&t=2924
